WP_DOMAIN=${WP_DOMAIN}
WP_MULTISITE=${WP_MULTISITE}
WP_MULTISITE_TYPE=${WP_MULTISITE_TYPE}
WP_PERSIST_UPLOADS=${WP_PERSIST_UPLOADS}
WP_INSTALL_LANGUAGES=${WP_INSTALL_LANGUAGES}
WP_INSTALL_PLUGINS=${WP_INSTALL_PLUGINS}
WP_ENVIRONMENT=${WP_ENVIRONMENT}
WP_THEMETEST=${WP_THEMETEST}